# Generated by Django 4.2.3 on 2024-05-08 01:00

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[news.models.validate_max_length],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=200,
                        validators=[news.models.validate_max_length],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=200,
                        validators=[news.models.validate_max_length],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        max_length=200,
                        validators=[news.models.validate_max_length],
                    ),
                ),
            ],
        ),
    ]
