# Generated by Django 4.2.3 on 2024-05-21 13:39

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            news.models.validate_max_length,
                            news.models.validate_title_word_count,
                            news.models.validate_field_word_count,
                        ],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[news.models.validate_field_word_count]
                    ),
                ),
                ("created_at", models.DateField()),
                ("image", models.ImageField(blank=True, upload_to="img/")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.user",
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.category",
                    ),
                ),
            ],
        ),
    ]
