# Generated by Django 4.2.3 on 2024-05-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="categories",
        ),
        migrations.AddField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(to="news.category"),
        ),
    ]
